apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nestjs-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nestjs-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nestjs-service.name" . }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appPort }} 
          livenessProbe:
            tcpSocket:
              port: {{ .Values.appPort }} 
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.appPort }} 
            initialDelaySeconds: 5
            periodSeconds: 3