apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
  selector:
    app.kubernetes.io/name: {{ include "nestjs-service.name" . }}