appName: "nestjs-service"
image:
  repository: "shivkumar1911/{{ .Values.appName }}"
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: ClusterIP
  port: 15332
  targetPort: 15332

replicaCount: 1

resources: {}